---
- name: Probe Host
  hosts: localhost  # configured to run locally
  connection:  locally  # configured to run locally
  gather_facts: no  # disables gathering effects to reduce playbook runtime
  # specifies three tasks
  tasks: 
  - name: Set Facts     # defnines env variables
    set_fact:
      probe_host: "{{ lookup('env', 'PROBE_HOST') }}"     # here we use lookup folter, those variabeles (ex: PROBE_HOST) must be set_fact
      probe_port: "{{ lookup('env', 'PROB_PORT') }}"
      probe_delay: "{{ lookup('env', 'PROB_DELAY') | default(0, true) }}"
      probe_timeout: "{{ lookup('env', 'PROBE_TIMEOUT') | default(180, true) }}"
  - name: Message   # prints a message to console
    debug:
      msg: >
       Probing {{ probe_host }}:{{ probe_port }} with delay={{ probe_delay }}s and timeout {{ probe_timeout }}s
  - name: Wating for the host to responde...  " Waits until a TCP connection can be sucessfully established"
    local_action: >
      wait_for host={{ probe_host }}
      port={{ probe_port }}
      delay={{ probe_delay }}
      timeout={{ probe_timeout }}